projects:
  prisma:
    schemaPath: "../src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
      codegen:
        generator: prisma-binding
        output:
          binding: ../src/generated/prisma.ts
        language: typescript
