projects:
  prisma:
    schemaPath: "../src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: ../src/generated/prisma.ts
        generator: prisma-ts
