version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.9
    restart: "no"
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: "mymanagementsecret123"
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
  db:
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
